name: check language tour

on:
  pull_request:
    branches: main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: moonbit-tour/package.json
      - name: check
        run: |
          cd moonbit-tour
          pnpm install
          pnpm build
